monsieurbiz_contact_request_admin_contact_request:
    resource: |
        alias: monsieurbiz_contact_request.contact_request
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: index
        except: ['update', 'create']
        grid: monsieurbiz_contact_request
    type: sylius.resource
