services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    MonsieurBiz\SyliusContactRequestPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    # Save contact request entity
    MonsieurBiz\SyliusContactRequestPlugin\EmailManager\DecorateContactEmailManager:
        decorates: 'sylius.email_manager.contact'
        arguments: [ '@.inner' ]

    # Add admin menu
    MonsieurBiz\SyliusContactRequestPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, priority: -100 }

    # Custom contact request factory
    MonsieurBiz\SyliusContactRequestPlugin\Factory\ContactRequestFactory:
        decorates: 'monsieurbiz_contact_request.factory.contact_request'
        arguments: [ '@.inner' ]

